### ISSUE TITLE
Add labels for severity

### ISSUE THREAD

**Issue by maxice8** [maxice8/atools#10]
Add 3 labels to indicate the severity of the problem found

- ERROR (or FATAL): This definitively causes problems with abuild/aports and should be fixed immediatelly. i.g.: pkgver having `-r` `_r`, depending on package in upper repo, depending on package that doesn't exist.

- WARNING: This can very problably cause problems but in fine in some situations, this also applies to stuff that is optional to change but is very recommended.

- OPTIONAL: Minor stuff that can be changed or not depending on the maintainer.

**Comment by maxice8** [comment]
@Ikke

**Comment by Ikke** [comment]
Looks good to me. We need to decide what lint would fall in what category.

**Comment by maxice8** [comment]
I'll open a PR for each label i do and tag you, then we can discuss each separately, ok ?

**Comment by Ikke** [comment]
Sure. Not sure if we want to do that right away, but maybe we could give each lint a unique code as well to more precisely identify it?

**Comment by maxice8** [comment]
On Mon, May 27, 2019 at 12:42:34PM -0700, Kevin Daudt wrote:
> Sure. Not sure if we want to do that right away, but maybe we could give each lint a unique code as well to more precisely identify it?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/maxice8/atools/issues/10#issuecomment-496293098

they have a long name in alint.5.scd that is used with SKIP_ and all uppercase with - replaced with _ to skip a specific lint. Isn't it enough ?

**Comment by Ikke** [comment]
I think it would fit better with #9, but the idea is to have these identifiers in the linting output, similar to how shellcheck has unique codes for each lint.

**Comment by maxice8** [comment]
Yeah sure, i'll cook up a stable format to output then
