### ISSUE TITLE
Mark default-builddir-value, superfluous-cd-builddir as minor.

### ISSUE THREAD

**Issue by Ikke** [maxice8/atools#19]
The description of important says:

>  Might cause problems during build or when the package is delivered to
> users in certain situations. Should be fixed soon.

Neither of these will cause any issues, they are just a matter of codestyle / preference.

The description of minor says:

> Won't directly cause issues during build or when the package is
> delivered to users.  Should be fixed when convenient

That's more suitable for these kinds of issues, they should not be fixed as soon as possible, but when convenient.

**Comment by maxice8** [comment]
Fixed in 15.4
