### ISSUE TITLE
apkbuild-lint warns about quoted vars when newapkbuild disagrees

### ISSUE THREAD

**Issue by Cogitri** [maxice8/atools#20]
When creating a new package with newapkbuild like so: 

```
newapkbuild -d "A quick preview for Nautilus" -l "GPL-2.0-or-later" -u "https://gitlab.gnome.org/GNOME/sushi" -m sushi-3.32.1
```

It produces an APKBUILD that has pkgname and pkver quoted:

```
pkgname="sushi"
pkgver="3.32.1"
```

But apkbuild-lint warns now:

```
MP:[AL3]:testing/sushi/APKBUILD:3:pkgname must not be quoted
MP:[AL4]:testing/sushi/APKBUILD:4:pkgver must not be quoted
```

It'd be nice if the two tools agreed on something.

**Comment by maxice8** [comment]
Nobody wrote anything about this change and 99% of packages use unquoted for pkgname= and pkgver= this is a problem on newapkbuild until i'm shown documentation on it.
