### ISSUE TITLE
Compatibility: sourcing of file in current dir requires './

### ISSUE THREAD

**Issue by Ikke** [maxice8/atools#7]
When running `apkbuild-lint APKBUILD`, the following code:

```sh
srcdir="" . "$apkbuild" 2>/dev/null
```
does not work when using posix shell (bash in compatibility mode). It requires you to prefix the filename with `./`. This will silently skip all tests.

This does work under ash though.

**Comment by maxice8** [comment]
ok i'll do it after i finish answering my emails
