### ISSUE TITLE
Have stable output

### ISSUE THREAD

**Issue by maxice8** [maxice8/atools#9]
For integration with `ALE` and other linters.

**Comment by maxice8** [comment]
@maxwell-k

**Comment by maxice8** [comment]
@maxwell-k Please comment or give any idea on how the output should be, i just use atools for personal linting and as such have no way to know how people that want stable output want it.

**Comment by maxwell-k** [comment]
@maxice8 sorry if I've been slow to respond. I'm following along and will comment over in https://github.com/maxice8/atools/pull/16 . Thanks!
